"""Manage optional AI providers for RuleBot AI."""

from __future__ import annotations

import logging
from typing import Any

from core.settings import Settings
from llm.base import LLMError, LLMResult
from llm.gemini_client import GeminiClient

logger = logging.getLogger("rulebot.llm")


class LLMProviderManager:
    """Resolve and call configured AI providers."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.providers: dict[str, GeminiClient] = {
            "gemini": GeminiClient(
                api_key=self.settings.gemini_api_key,
                timeout=self.settings.request_timeout,
            )
        }

    def availability(self) -> dict[str, bool]:
        return {
            name: getattr(client, "available", False)
            for name, client in self.providers.items()
        }

    def has_available_provider(self) -> bool:
        return any(self.availability().values())

    def default_provider(self) -> str | None:
        return "gemini" if self.providers["gemini"].available else None

    async def generate(self, prompt: str, provider: str | None = None) -> LLMResult:
        selected = provider or self.default_provider()
        if selected is None:
            raise LLMError("No AI provider is configured.")

        if selected not in self.providers:
            raise LLMError(f"Unsupported AI provider: {selected}")

        client = self.providers[selected]
        if not client.available:
            raise LLMError(f"{selected} is not configured.")

        try:
            result = await client.generate(prompt)
            logger.info("AI response generated by %s", selected)
            return result
        except Exception as error:
            logger.warning("AI provider %s failed: %s", selected, error)
            raise LLMError("AI provider failed to generate a response.") from error
